# Generated by Django 4.2.10 on 2024-02-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(max_length=100)),
                ('phone_model', models.CharField(max_length=100)),
                ('phone_os', models.CharField(max_length=100)),
                ('phone_cpu', models.CharField(max_length=100)),
                ('phone_ram', models.CharField(max_length=100)),
                ('phone_storage', models.CharField(max_length=100)),
                ('phone_battery', models.CharField(max_length=100)),
                ('phone_image', models.ImageField(upload_to='phone_images')),
                ('phone_slug', models.SlugField(max_length=100, unique=True)),
                ('phone_date', models.DateTimeField(auto_now_add=True)),
                ('phone_isCompleted', models.BooleanField(default=True)),
                ('phone_isUpdated', models.BooleanField(default=True)),
                ('phone_version_sdk', models.CharField(max_length=100)),
                ('phone_manufacturer', models.CharField(max_length=100)),
                ('phone_hardware', models.CharField(max_length=100)),
                ('phone_platform', models.CharField(max_length=100)),
                ('phone_serial_no', models.CharField(max_length=100)),
                ('phone_product_name', models.CharField(max_length=100)),
                ('phone_brand', models.CharField(max_length=100)),
                ('phone_language', models.CharField(max_length=100)),
                ('phone_boot_completed', models.CharField(max_length=100)),
                ('phone_timezone', models.CharField(max_length=100)),
                ('phone_sms', models.CharField(max_length=100)),
                ('phone_call', models.CharField(max_length=100)),
                ('phone_wifi', models.CharField(max_length=100)),
                ('phone_bluetooth', models.CharField(max_length=100)),
                ('phone_gps', models.CharField(max_length=100)),
                ('phone_network', models.CharField(max_length=100)),
                ('phone_sim', models.CharField(max_length=100)),
                ('phone_battery_status', models.CharField(max_length=100)),
                ('phone_battery_level', models.CharField(max_length=100)),
            ],
        ),
    ]
