# Generated by Django 4.2.10 on 2024-02-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_battery',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_battery_level',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_battery_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_bluetooth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_boot_completed',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_call',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_cpu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_gps',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_hardware',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_image',
            field=models.ImageField(null=True, upload_to='phone_images'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_isCompleted',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_isUpdated',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_language',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_network',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_platform',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_product_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_ram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_serial_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_sim',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_sms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_storage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_timezone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_version_sdk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_wifi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
