# Generated by Django 4.2.10 on 2024-02-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_info', '0002_alter_phone_phone_battery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
