# Generated by Django 4.2.10 on 2024-02-26 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_info', '0005_alter_phone_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='phone_info.category'),
        ),
    ]
