# Generated by Django 4.2.10 on 2024-02-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_info', '0006_phone_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_image',
            field=models.ImageField(default='static/images/phones/default.jpg', null=True, upload_to='static/images/phones/'),
        ),
    ]
