# Generated by Django 4.2.10 on 2024-02-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_info', '0007_alter_phone_phone_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='category',
        ),
        migrations.AddField(
            model_name='phone',
            name='categories',
            field=models.ManyToManyField(related_name='phones', to='phone_info.category'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
