# Generated by Django 4.2.10 on 2024-02-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_info', '0008_remove_phone_category_phone_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='phone_isActive',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='phone_isHome',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
