# Generated by Django 4.2.10 on 2024-02-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_info', '0010_alter_phone_categories_alter_phone_phone_battery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
