# Generated by Django 4.2.10 on 2024-03-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_info', '0012_alter_phone_phone_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='phone_cpu',
            new_name='phone_operator',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='phone_ram',
            new_name='phone_status',
        ),
    ]
