# Generated by Django 4.2.10 on 2024-03-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_info', '0013_rename_phone_cpu_phone_phone_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
