# Generated by Django 4.2.10 on 2024-04-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_info', '0014_alter_phone_phone_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_operator',
            field=models.CharField(blank=True, choices=[('Turkcell', 'Turkcell'), ('Vodafone', 'Vodafone'), ('Türk Telekom', 'Türk Telekom')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_os',
            field=models.CharField(blank=True, choices=[('Android', 'Android'), ('IOS', 'IOS'), ('HarmonyOS', 'HarmonyOS')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_status',
            field=models.CharField(blank=True, choices=[('Sifreli', 'Şifreli'), ('Sifresiz', 'Şifresiz')], max_length=100, null=True),
        ),
    ]
